#+TITLE: # 3rd year SOFTWARE PROJECT at Polytech' Grenoble
#+AUTHOR: Alexis LANQUETIN, Polytech'Grenoble, Univ. Grenoble Alpes
#+DATE: October 2020

* I. Kusinta

Kusinta is a /rogue-like/ video game. This kind of game is
#+BEGIN_SRC ascii
characterized by a dungeon crawl through procedurally generated levels, turn-based gameplay, tile-based graphics, and permanent death of the player character.
Taken from Wikipedia
#+END_SRC

In Kusinta, the player explores a dungeon, kills the monsters within and climbs to the next room.
All the monsters drop gold, and one in each room drops the key to the next room. When the player loots the key, a door to the next room appears.
At any time, he can go back to the village and buy equipment to increase his power.

* II. The Village

In the village, the player has a menu on the left, where he can
*** Go in the Dungeon (Adventure)
*** See his equipment (Inventory)
*** Buy more equipment (Weapon Shop)
*** Buy potions (Magic Shop)

** * Inventory

Here, the player can see his equipment and sell it.

** * Weapon Shop

Here, the player as a large choice of equipment, generated based on the level of his current equipment. The better is the player's equipment, the greater (and the more expansive) the equipment available is. If he buys an equipment type he already owns, the equipped one is automatically sold and replaced by the new one.
For some gold, he can redraw equipment, if he doesn't like the current set.

** * Magic Shop

There is two different potions. Both heals the player when he is in the dungeon but one is a small potion (cheaper) and the other is a big one.

** * Stats & Equipment

The player has 4 stats:
 - Strength: damage dealt to the monsters
 - Resistance: reduce damage taken from monsters attacks
 - Attack speed: in millisecond, the time between two attacks
 - Life

 Equipment improves these stats. There is 8 different equipment types and the player can wear only 1 of each at the same time.

 The stats modification of the equipment is randomly generated, based on the level of the equipment. Its price is calculated based on the power of these modifications.

* III. The Dungeon

Each room is randomly generated. There is a pattern to make the room viable but both the size and the decoration are different in every room.

There is also 3 different visuals for the room, which make all the rooms "unique".

The player slays monsters with a long bow. He can jump, move left and right.

** * Rooms

Each room is a level. The player first spawns in the level-1 room, and climb to the level-2 room, and so on.
The higher the room level is, the stronger the monsters are. However, only a high ranking room can deliver the boss key. In fact, it's most likely for a monster to drop the boss key if the room is of an higher level.
At any time, the player can go back to the village and spend his money, but he will restart the dungeon in a level-1 room.
Only one monster per level can drop the key to the next room. When it's dead, the door appears, as well as a compass showing the direction to this door throughout the room.

** * Monsters

There are 5 different monsters:
- the Djinn : flying and ranged opponent
- the Medusa : not resistant but strong and fast on foot opponent
- the Demon : resistant but weak and slow on foot opponent
- the mini Dragon : immortal ranged on foot opponent
- the Dragon (boss) : flying, ranged, strong opponent

Each dead monster drops gold. But the stronger the player is, the lower the gain is. In fact, the player can't repeatedly loot the first room (which becomes very simple when he gains power), because the income sharply drops with higher player equipment.

* IV. The Underworld

The Underworld is the second world of Kusinta. It's also called "The second chance world". When the player dies, he must find all the fragments of his soul to resuscitate, while facing the ghosts of all the monsters he killed. 

When he recovers his soul, a portal appears to teleport him back in the dungeon, exactly where he died.

But in the underworld, ghosts will chase him and trying to kill him.

The player can create a lure to distract the ghosts, they will attack the lure instead of the player.

If the player dies in the Underworld, it's game over.


* [[README.md][BACK]]

---
    AUTHOR: Alexis LANQUETIN, Polytech'Grenoble, Univ. Grenoble Alpes
    DATE: October 2020
